import type { CardDef, Rarity } from './types';
import { commandChoices } from './commands';

/**
 * The second set: a hundred cards for building decks, alongside the first set (the starter decks use
 * only the first). They use the same mechanics, in new mixes, so every race has more ways to play
 * its game: Aureline lancers stacking attack cards, Xel'Naru running their sun hot, Vorthane
 * hoarding shields, the Ixquor hive going wide and growing.
 */
export const EXPANSION: CardDef[] = [
  // ---- Neutral attack ----
  { id: 'nova_shell', name: 'Nova Shell', kind: 'attack', text: '{heat:2}. {shield:1}.', onPlay: [{ type: 'heat', amount: 2, to: 'target' }, { type: 'shield', amount: 1 }] },
  { id: 'photon_drill', name: 'Photon Drill', kind: 'attack', text: '{heat:2}, {pierce}.', onPlay: [{ type: 'heat', amount: 2, to: 'target', pierce: true }] },
  {
    id: 'ember_drone',
    name: 'Ember Drone',
    kind: 'attack',
    text: '{dawn}: {heat:1}. When this leaves your tableau, {heat:1}.',
    onTurn: [{ type: 'heat', amount: 1, to: 'target' }],
    onLeave: [{ type: 'heat', amount: 1, to: 'target' }],
  },
  {
    id: 'siege_array',
    name: 'Siege Array',
    kind: 'attack',
    text: '{dawn}: {heat:1}. {heat:+1} per 3 attack cards (up to 2).',
    onTurn: [{ type: 'heat', amount: 1, to: 'target', plus: { of: 'kind', kind: 'attack', per: 3 }, max: 2 }],
  },
  { id: 'scatter_shot', name: 'Scatter Shot', kind: 'attack', text: '{heat:2}. {erode:1}.', onPlay: [{ type: 'heat', amount: 2, to: 'target' }, { type: 'erode', amount: 1 }] },
  {
    id: 'flux_lance',
    name: 'Flux Lance',
    kind: 'attack',
    text: '{heat:2}. Draw 1. {heat:1} to your sun.',
    onPlay: [{ type: 'heat', amount: 2, to: 'target' }, { type: 'draw', amount: 1 }, { type: 'selfHeat', amount: 1 }],
  },
  { id: 'void_bolt', name: 'Void Bolt', kind: 'attack', text: '{destroy:1}. {heat:2}.', onPlay: [{ type: 'destroy', maxDefence: 1 }, { type: 'heat', amount: 2, to: 'target' }] },

  {
    id: 'comet_hail',
    name: 'Comet Hail',
    kind: 'attack',
    text: '{dawn}: {heat:1}. {heat:+1} while facing the industrial planet.',
    onTurn: [{ type: 'heat', amount: 1, to: 'target', plus: { of: 'planet', planet: 'industrial', amount: 1 } }],
  },

  // ---- Neutral defence ----
  { id: 'frost_lattice', name: 'Frost Lattice', kind: 'defence', text: '{dawn}: {shield:1}. {dusk}: {cool:1}.', onTurn: [{ type: 'shield', amount: 1 }], onDusk: [{ type: 'cool', amount: 1 }] },
  { id: 'mirror_plating', name: 'Mirror Plating', kind: 'defence', text: '{shield:4}.', onPlay: [{ type: 'shield', amount: 4 }] },
  { id: 'cold_front', name: 'Cold Front', kind: 'defence', text: '{cool:2}. {shield:1}.', onPlay: [{ type: 'cool', amount: 2 }, { type: 'shield', amount: 1 }] },
  {
    id: 'radiator_fins',
    name: 'Radiator Fins',
    kind: 'defence',
    text: '{dusk}: {cool:1}. {cool:+1} while {overheated}.',
    onDusk: [{ type: 'cool', amount: 1 }, { type: 'cool', amount: 1, if: { overheated: true } }],
  },
  { id: 'bastion_node', name: 'Bastion Node', kind: 'defence', text: '{guard}. {sturdy:3}. {dawn}: {shield:1}.', defence: 3, onTurn: [{ type: 'shield', amount: 1 }], passive: [{ type: 'taunt' }] },
  // Lightspeed guards: played as a Guard, or set face down (1 more energy) to spring in front of an aimed-at card.
  {
    id: 'blink_bulwark',
    name: 'Blink Bulwark',
    kind: 'defence',
    text: '{guard}. {sturdy:1}. {dawn}: {shield:1}. {lightspeed} for 1 more energy: springs into your tableau to take an attack or heat aimed at your cards.',
    defence: 1,
    onTurn: [{ type: 'shield', amount: 1 }],
    passive: [{ type: 'taunt' }],
    lightspeed: { trigger: { on: 'cardAttacked' }, deploy: true },
  },
  {
    id: 'sunflash_aegis',
    name: 'Sunflash Aegis',
    kind: 'defence',
    race: 0,
    text: '{guard}. {sturdy:1}. {dusk}: {cool:1}. {lightspeed} for 1 more energy: springs into your tableau to take an attack or heat aimed at your cards.',
    defence: 1,
    onDusk: [{ type: 'cool', amount: 1 }],
    passive: [{ type: 'taunt' }],
    lightspeed: { trigger: { on: 'cardAttacked' }, deploy: true },
  },
  {
    id: 'riptide_sentinel',
    name: 'Riptide Sentinel',
    kind: 'defence',
    race: 2,
    text: '{guard}. {sturdy:2}. {dawn}: {shield:2}. {lightspeed} for 1 more energy: springs into your tableau to take an attack or heat aimed at your cards.',
    defence: 2,
    onTurn: [{ type: 'shield', amount: 2 }],
    passive: [{ type: 'taunt' }],
    lightspeed: { trigger: { on: 'cardAttacked' }, deploy: true },
  },
  {
    id: 'debris_field',
    name: 'Debris Field',
    kind: 'defence',
    text: '{shield:2}. {dawn}: {shield:1}.',
    onPlay: [{ type: 'shield', amount: 2 }],
    onTurn: [{ type: 'shield', amount: 1 }],
  },

  // ---- Neutral growth ----
  { id: 'survey_probe', name: 'Survey Probe', kind: 'growth', text: 'Your {orbit:+3}. {cool:1}.', onPlay: [{ type: 'orbit', amount: 3, who: 'self' }, { type: 'cool', amount: 1 }] },
  { id: 'star_chart', name: 'Star Chart', kind: 'growth', text: '{restore:2}. Draw 1.', onPlay: [{ type: 'restore', amount: 2 }, { type: 'draw', amount: 1 }] },
  {
    id: 'gravity_well',
    name: 'Gravity Well',
    kind: 'growth',
    text: "Your rival's {orbit:−3}: their planet slips back. {heat:1}.",
    onPlay: [{ type: 'orbit', amount: -3, who: 'rival' }, { type: 'heat', amount: 1, to: 'target' }],
  },
  {
    id: 'relay_station',
    name: 'Relay Station',
    kind: 'growth',
    text: '{energy:1}. {heat:1} to your sun.',
    onPlay: [{ type: 'plays', amount: 1 }, { type: 'selfHeat', amount: 1 }],
  },
  { id: 'archive_vault', name: 'Archive Vault', kind: 'growth', text: '{recover}. Draw 1.', onPlay: [{ type: 'recover', orDraw: 1 }, { type: 'draw', amount: 1 }] },
  { id: 'supply_cache', name: 'Supply Cache', kind: 'growth', text: '{dawn}: with 3+ cards, draw 1.', onTurn: [{ type: 'draw', amount: 1, if: { minCards: 3 } }] },

  // ---- Neutral lightspeed ----
  {
    id: 'flare_trap',
    name: 'Flare Trap',
    kind: 'lightspeed',
    text: "{lightspeed}. When an enemy's card is about to heat your sun, first {heat:2} to them.",
    lightspeed: { trigger: { on: 'heated' }, effects: [{ type: 'heat', amount: 2, to: 'target' }] },
  },
  {
    id: 'counter_pulse',
    name: 'Counter-Pulse',
    kind: 'lightspeed',
    text: '{lightspeed}. When an enemy plays an attack card, first {shield:4}.',
    lightspeed: { trigger: { on: 'enemyPlays', kind: 'attack' }, effects: [{ type: 'shield', amount: 4 }] },
  },
  {
    id: 'snare_beacon',
    name: 'Snare Beacon',
    kind: 'lightspeed',
    text: '{lightspeed}. When an enemy plays a card, {cool:2}. Draw 1.',
    lightspeed: { trigger: { on: 'enemyPlays' }, effects: [{ type: 'cool', amount: 2 }, { type: 'draw', amount: 1 }] },
  },
  {
    id: 'ghost_signal',
    name: 'Ghost Signal',
    kind: 'lightspeed',
    text: '{lightspeed}. When an enemy plays a support card, {heat:2} to them. Draw 1.',
    lightspeed: { trigger: { on: 'enemyPlays', kind: 'growth' }, effects: [{ type: 'heat', amount: 2, to: 'target' }, { type: 'draw', amount: 1 }] },
  },

  // ---- Neutral Command ----
  // Hero leaders (Command cards): a Xel'Naru Archon and an Ixquor Hive-Speaker.
  { id: 'war_council', name: 'Archon Seris', kind: 'command', race: 1, text: '{dawn}, one of: {options:energy1|draw1|recover1}', choices: commandChoices('energy1', 'draw1', 'recover1') },
  { id: 'logistics_command', name: 'Hive-Speaker Zyth', kind: 'command', race: 3, text: '{dawn}, one of: {options:energy1|draw1|orbit1}', choices: commandChoices('energy1', 'draw1', 'orbit1') },
  // ---- Thermosiphon: stronger the further your sun is below zero ----
  { id: 'absolute_zero', name: 'Absolute Zero', kind: 'attack', race: 1, text: '{cool:2}. {dawn}: {heat:1}. {thermosiphon} {heat:1}.', onPlay: [{ type: 'cool', amount: 2 }], onTurn: [{ type: 'heat', amount: 1, to: 'target' }, { type: 'heat', amount: 0, to: 'target', plus: { of: 'cold', per: 2 } }] },
  { id: 'cryo_lance', name: 'Cryo Lance', kind: 'attack', race: 1, text: '{heat:2}, {pierce}. {thermosiphon} {heat:1}, {pierce}.', onPlay: [{ type: 'heat', amount: 2, to: 'target', pierce: true }, { type: 'heat', amount: 0, to: 'target', plus: { of: 'cold', per: 2 }, pierce: true }] },
  { id: 'rime_bastion', name: 'Rime Bastion', kind: 'defence', text: '{sturdy:2}. {dawn}: {shield:1}. {thermosiphon} {shield:1}.', defence: 2, onTurn: [{ type: 'shield', amount: 1 }, { type: 'shield', amount: 0, plus: { of: 'cold', per: 2 } }] },
  { id: 'frostbound_sentinel', name: 'Frostbound Sentinel', kind: 'defence', race: 1, text: '{guard}. {sturdy:1}. {dawn}: {shield:1}. {thermosiphon} {shield:1}.', defence: 1, onTurn: [{ type: 'shield', amount: 1 }, { type: 'shield', amount: 0, plus: { of: 'cold', per: 2 } }], passive: [{ type: 'taunt' }] },
  { id: 'glacier_hull', name: 'Glacier Hull', kind: 'defence', race: 2, text: '{shield:2}. {hold}. {dawn}: {shield:1}. {thermosiphon} {shield:1}.', onPlay: [{ type: 'shield', amount: 2 }], onTurn: [{ type: 'shield', amount: 1 }, { type: 'shield', amount: 0, plus: { of: 'cold', per: 2 } }], passive: [{ type: 'keepShields' }] },
  { id: 'thaw_beam', name: 'Thaw Beam', kind: 'attack', text: "{heat:1}, {pierce}. {heat:+1} per 2 points your target's sun is below zero.", onPlay: [{ type: 'heat', amount: 1, to: 'target', plus: { of: 'cold', rival: true, per: 2 }, pierce: true }] },
  // ---- The galaxy eater: denies every rival its planets ----
  { id: 'orion_galaxy_eater', name: 'Orion, Galaxy Eater', kind: 'growth', text: "{sturdy:1}. Your rivals' planets are all dead planets: no Industry or Abundance from them.", defence: 1, passive: [{ type: 'eatPlanets' }] },
  // ---- Bomb Heroes: a big entrance for a big price ----
  { id: 'empress_solenne', name: 'Empress Solenne', kind: 'command', race: 0, text: '{heat:4}, {pierce}. {dawn}, one of: {options:energy1|draw1|heat3}', onPlay: [{ type: 'heat', amount: 4, to: 'target', pierce: true }], choices: commandChoices('energy1', 'draw1', 'heat3') },
  { id: 'the_shardmind', name: 'The Shardmind', kind: 'command', race: 1, text: '{cool:4}, {recover}. {dawn}, one of: {options:energy1|draw1|cool3}', onPlay: [{ type: 'cool', amount: 4 }, { type: 'recover', orDraw: 1 }], choices: commandChoices('energy1', 'draw1', 'cool3') },
  { id: 'leviathan_thoross', name: 'Leviathan Thoross', kind: 'command', race: 2, text: '{shield:6}, {eject:3}. {dawn}, one of: {options:energy1|draw1|shield5}', onPlay: [{ type: 'shield', amount: 6 }, { type: 'bounce', maxDefence: 3 }], choices: commandChoices('energy1', 'draw1', 'shield5') },
  { id: 'the_worldroot', name: 'The Worldroot', kind: 'command', race: 3, text: 'Draw 3, {renew:2}. {dawn}, one of: {options:energy1|draw1|renew2}', onPlay: [{ type: 'draw', amount: 3 }, { type: 'restore', amount: 2, all: true }], choices: commandChoices('energy1', 'draw1', 'renew2') },

  // ---- Aureline ----
  {
    id: 'aureline_skirmisher',
    name: 'Aureline Skirmisher',
    kind: 'attack',
    race: 0,
    text: '{heat:1}. {dawn}: {heat:1}.',
    onPlay: [{ type: 'heat', amount: 1, to: 'target' }],
    onTurn: [{ type: 'heat', amount: 1, to: 'target' }],
  },
  {
    id: 'dawnblade',
    name: 'Dawnblade',
    kind: 'attack',
    race: 0,
    text: '{heat:3}. {heat:+1} with 3+ attack cards.',
    onPlay: [{ type: 'heat', amount: 3, to: 'target' }, { type: 'heat', amount: 1, to: 'target', if: { minKind: 'attack', n: 3 } }],
  },
  {
    id: 'lancer_squadron',
    name: 'Lancer Squadron',
    kind: 'attack',
    race: 0,
    text: '{heat:2}. {heat:+1} per 2 attack cards (up to 4).',
    onPlay: [{ type: 'heat', amount: 2, to: 'target', plus: { of: 'kind', kind: 'attack', per: 2 }, max: 4 }],
  },
  {
    id: 'aureline_archon',
    name: 'Aureline Archon',
    kind: 'attack',
    race: 0,
    text: '{dawn}: {heat:3}. {heat:+1} with a Hero.',
    onTurn: [{ type: 'heat', amount: 3, to: 'target' }, { type: 'heat', amount: 1, to: 'target', if: { minKind: 'command', n: 1 } }],
  },
  {
    id: 'the_sun_throne',
    name: 'The Sun Throne',
    kind: 'growth',
    race: 0,
    text: 'Your attack cards deal +1 {heat}. Draw 2.',
    onPlay: [{ type: 'draw', amount: 2 }],
    passive: [{ type: 'kindBonus', kind: 'attack', amount: 1 }],
  },
  {
    id: 'gilded_lens',
    name: 'Gilded Lens',
    kind: 'growth',
    race: 0,
    text: '{forge:1}. Draw 1.',
    onPlay: [{ type: 'draw', amount: 1 }],
    passive: [{ type: 'adjacent', amounts: [1], kind: 'attack' }],
  },
  {
    id: 'radiant_hymn',
    name: 'Radiant Hymn',
    kind: 'growth',
    race: 0,
    text: 'Draw 1. {dusk}: with a Hero, {cool:1}.',
    onPlay: [{ type: 'draw', amount: 1 }],
    onDusk: [{ type: 'cool', amount: 1, if: { minKind: 'command', n: 1 } }],
  },
  {
    id: 'solar_aegis',
    name: 'Solar Aegis',
    kind: 'defence',
    race: 0,
    text: '{shield:2}. {shield:+1} per 2 attack cards.',
    onPlay: [{ type: 'shield', amount: 2, plus: { of: 'kind', kind: 'attack', per: 2 } }],
  },
  {
    id: 'aureline_cantor',
    name: 'Aureline Cantor',
    kind: 'defence',
    race: 0,
    text: '{dawn}: {shield:1}. {dusk}: {cool:2} with 3+ attack cards.',
    onTurn: [{ type: 'shield', amount: 1 }], onDusk: [{ type: 'cool', amount: 2, if: { minKind: 'attack', n: 3 } }],
  },
  { id: 'lance_volley', name: 'Lance Volley', kind: 'attack', race: 0, text: '{heat:1}. {restore:2}.', onPlay: [{ type: 'heat', amount: 1, to: 'target' }, { type: 'restore', amount: 2 }] },
  {
    id: 'glory_charge',
    name: 'Glory Charge',
    kind: 'attack',
    race: 0,
    text: '{heat:2}. {energy:1}. {heat:1} to your sun.',
    onPlay: [{ type: 'heat', amount: 2, to: 'target' }, { type: 'plays', amount: 1 }, { type: 'selfHeat', amount: 1 }],
  },
  {
    id: 'banner_of_dawn',
    name: 'Banner of Dawn',
    kind: 'growth',
    race: 0,
    text: 'Draw 1. {dawn}: with 3+ attack cards, {heat:1}.',
    onPlay: [{ type: 'draw', amount: 1 }],
    onTurn: [{ type: 'heat', amount: 1, to: 'target', if: { minKind: 'attack', n: 3 } }],
  },
  {
    id: 'halo_sentinel',
    name: 'Halo Sentinel',
    kind: 'defence',
    race: 0,
    text: '{guard}. {sturdy:1}. {dawn}: {shield:1}. {shield:+1} with a Hero.',
    defence: 1,
    onTurn: [{ type: 'shield', amount: 1 }, { type: 'shield', amount: 1, if: { minKind: 'command', n: 1 } }], passive: [{ type: 'taunt' }] },
  {
    id: 'prism_of_dawn',
    name: 'Prism of Dawn',
    kind: 'lightspeed',
    race: 0,
    text: '{lightspeed}. When an enemy plays an attack card, {heat:2} to them and {shield:2}.',
    lightspeed: { trigger: { on: 'enemyPlays', kind: 'attack' }, effects: [{ type: 'heat', amount: 2, to: 'target' }, { type: 'shield', amount: 2 }] },
  },
  {
    id: 'sunfire_volley',
    name: 'Sunfire Volley',
    kind: 'attack',
    race: 0,
    text: '{heat:1} per attack card you control (up to 3). {cool:1}.',
    onPlay: [{ type: 'heat', amount: 0, to: 'target', plus: { of: 'kind', kind: 'attack' }, max: 3 }, { type: 'cool', amount: 1 }],
  },
  {
    id: 'aureline_quartermaster',
    name: 'Aureline Quartermaster',
    kind: 'growth',
    race: 0,
    text: '{recover:attack}. {shield:1}.',
    onPlay: [{ type: 'recover', kind: 'attack', orDraw: 1 }, { type: 'shield', amount: 1 }],
  },
  {
    id: 'helio_bastion',
    name: 'Helio Bastion',
    kind: 'defence',
    race: 0,
    text: '{forge:1}. {dusk}: {cool:1}.',
    onDusk: [{ type: 'cool', amount: 1 }],
    passive: [{ type: 'adjacent', amounts: [1], kind: 'attack' }],
  },
  {
    id: 'aureline_vanguard',
    name: 'Aureline Vanguard',
    kind: 'attack',
    race: 0,
    text: '{sturdy:1}. {shield:1}. {dawn}: {heat:1}.',
    defence: 1,
    onPlay: [{ type: 'shield', amount: 1 }],
    onTurn: [{ type: 'heat', amount: 1, to: 'target' }],
  },
  {
    id: 'sunlance_charge',
    name: 'Sunlance Charge',
    kind: 'attack',
    race: 0,
    text: '{heat:2}. {heat:+2} with a Hero.',
    onPlay: [{ type: 'heat', amount: 2, to: 'target' }, { type: 'heat', amount: 2, to: 'target', if: { minKind: 'command', n: 1 } }],
  },

  // ---- Xel'Naru ----
  {
    id: 'shard_lancer',
    name: "Xel'Naru Shardlancer",
    kind: 'attack',
    race: 1,
    text: '{heat:3}, {pierce}. {heat:1} to your sun.',
    onPlay: [{ type: 'heat', amount: 3, to: 'target', pierce: true }, { type: 'selfHeat', amount: 1 }],
  },
  {
    id: 'searing_core',
    name: 'Searing Core',
    kind: 'attack',
    race: 1,
    text: '{dawn}: {heat:1}, {pierce}. {heat:+1} while {overheated}.',
    onTurn: [{ type: 'heat', amount: 1, to: 'target', pierce: true }, { type: 'heat', amount: 1, to: 'target', pierce: true, if: { overheated: true } }],
  },
  {
    id: 'crystal_bloom',
    name: 'Crystal Bloom',
    kind: 'defence',
    race: 1,
    text: '{cool:2}. {cool:+2} while {overheated}.',
    onPlay: [{ type: 'cool', amount: 2 }, { type: 'cool', amount: 2, if: { overheated: true } }],
  },
  {
    id: 'fault_line',
    name: 'Fault Line',
    kind: 'attack',
    race: 1,
    text: '{erode:2}. {heat:2}. {heat:1} to your sun.',
    onPlay: [{ type: 'erode', amount: 2 }, { type: 'heat', amount: 2, to: 'target' }, { type: 'selfHeat', amount: 1 }],
  },
  {
    id: 'echo_shard',
    name: 'Echo Shard',
    kind: 'attack',
    race: 1,
    text: '{heat:1}. When this leaves your tableau, {heat:2}.',
    onPlay: [{ type: 'heat', amount: 1, to: 'target' }],
    onLeave: [{ type: 'heat', amount: 2, to: 'target' }],
  },
  {
    id: 'shatter_point',
    name: 'Shatter Point',
    kind: 'attack',
    race: 1,
    text: '{destroy:3}. {heat:2} to your sun.',
    onPlay: [{ type: 'destroy', maxDefence: 3 }, { type: 'selfHeat', amount: 2 }],
  },
  {
    id: 'prism_ward',
    name: 'Prism Ward',
    kind: 'defence',
    race: 1,
    text: '{dusk}: {cool:1}. When this leaves your tableau, {cool:3}.',
    onDusk: [{ type: 'cool', amount: 1 }],
    onLeave: [{ type: 'cool', amount: 3 }],
  },
  {
    id: 'xelnaru_oracle',
    name: "Xel'Naru Oracle",
    kind: 'growth',
    race: 1,
    text: 'Draw 1. {dawn}: while {overheated}, draw 1.',
    onPlay: [{ type: 'draw', amount: 1 }],
    onTurn: [{ type: 'draw', amount: 1, if: { overheated: true } }],
  },
  {
    id: 'molten_cascade',
    name: 'Molten Cascade',
    kind: 'attack',
    race: 1,
    text: '{heat:1} per 2 cards you control (up to 3), {pierce}.',
    onPlay: [{ type: 'heat', amount: 0, to: 'target', plus: { of: 'cards', per: 2 }, max: 3, pierce: true }],
  },
  {
    id: 'shard_storm',
    name: 'Shard Storm',
    kind: 'attack',
    race: 1,
    text: '{heat:2}. {heat:+2} while {overheated}. {heat:1} to your sun.',
    onPlay: [{ type: 'heat', amount: 2, to: 'target' }, { type: 'heat', amount: 2, to: 'target', if: { overheated: true } }, { type: 'selfHeat', amount: 1 }],
  },
  { id: 'heat_bleed', name: 'Heat Bleed', kind: 'defence', race: 1, text: '{cool:3}. {heat:1}.', onPlay: [{ type: 'cool', amount: 3 }, { type: 'heat', amount: 1, to: 'target' }] },
  {
    id: 'crystal_matrix',
    name: 'Crystal Matrix',
    kind: 'growth',
    race: 1,
    text: '{resonance:2}. {dawn}: {heat:1} to your sun.',
    onTurn: [{ type: 'selfHeat', amount: 1 }],
    passive: [{ type: 'adjacent', amounts: [2] }],
  },
  {
    id: 'xelnaru_warden',
    name: "Xel'Naru Warden",
    kind: 'defence',
    race: 1,
    text: '{guard}. {sturdy:1}. {dusk}: {cool:1}. {cool:+1} while {overheated}.',
    defence: 1,
    onDusk: [{ type: 'cool', amount: 1 }, { type: 'cool', amount: 1, if: { overheated: true } }], passive: [{ type: 'taunt' }] },
  { id: 'shard_echo', name: 'Shard Echo', kind: 'growth', race: 1, text: '{recall}. {cool:1}.', onPlay: [{ type: 'recall' }, { type: 'cool', amount: 1 }] },
  // More recall, for every deck: a card that comes back to be played again (and the recall card can take its slot).
  { id: 'tactical_withdrawal', name: 'Tactical Withdrawal', kind: 'growth', text: '{recall}. Your {orbit:+3}.', onPlay: [{ type: 'recall' }, { type: 'orbit', amount: 3, who: 'self' }] },
  { id: 'rally_banner', name: 'Rally Banner', kind: 'attack', race: 0, text: '{recall}. {heat:1}.', onPlay: [{ type: 'recall' }, { type: 'heat', amount: 1, to: 'target' }] },
  { id: 'spore_return', name: 'Spore Return', kind: 'growth', race: 3, text: '{recall}. {renew:1}.', onPlay: [{ type: 'recall' }, { type: 'restore', amount: 1, all: true }] },
  {
    id: 'overcharge',
    name: 'Overcharge',
    kind: 'growth',
    race: 1,
    text: '{energy:1}. Draw 1. {heat:1} to your sun.',
    onPlay: [{ type: 'plays', amount: 1 }, { type: 'draw', amount: 1 }, { type: 'selfHeat', amount: 1 }],
  },
  {
    id: 'refraction_veil',
    name: 'Refraction Veil',
    kind: 'lightspeed',
    race: 1,
    text: "{lightspeed}. When an enemy's card is about to heat your sun, cancel that. {heat:1} to your sun.",
    lightspeed: { trigger: { on: 'heated' }, counter: true, effects: [{ type: 'selfHeat', amount: 1 }] },
  },
  {
    id: 'shard_mother',
    name: "Xel'Naru Shard-Mother",
    kind: 'attack',
    race: 1,
    text: '{heat:2}. {dawn}: {heat:1}, {pierce}.',
    onPlay: [{ type: 'heat', amount: 2, to: 'target' }],
    onTurn: [{ type: 'heat', amount: 1, to: 'target', pierce: true }],
  },
  {
    id: 'fracture_burst',
    name: 'Fracture Burst',
    kind: 'attack',
    race: 1,
    text: '{heat:8}, {pierce}. {heat:2} to your sun.',
    onPlay: [{ type: 'heat', amount: 8, to: 'target', pierce: true }, { type: 'selfHeat', amount: 2 }],
  },
  { id: 'cinder_ward', name: 'Cinder Ward', kind: 'defence', race: 1, text: '{shield:2}. {cool:1}.', onPlay: [{ type: 'shield', amount: 2 }, { type: 'cool', amount: 1 }] },

  // ---- Vorthane ----
  {
    id: 'vorthane_tidecaller',
    name: 'Vorthanian Tidecaller',
    kind: 'defence',
    race: 2,
    text: '{dawn}: {shield:2}. {shield:+2} with 3+ defence cards.',
    onTurn: [{ type: 'shield', amount: 2 }, { type: 'shield', amount: 2, if: { minKind: 'defence', n: 3 } }],
  },
  {
    id: 'brine_lash',
    name: 'Brine Lash',
    kind: 'attack',
    race: 2,
    text: '{heat:2}. {heat:+1} per 2 shields you have (up to 4).',
    onPlay: [{ type: 'heat', amount: 2, to: 'target', plus: { of: 'shields', per: 2 }, max: 4 }],
  },
  { id: 'kelp_wall', name: 'Kelp Wall', kind: 'defence', race: 2, text: '{sturdy:1}. {shield:3}.', defence: 1, onPlay: [{ type: 'shield', amount: 3 }] },
  {
    id: 'abyss_lantern',
    name: 'Vorthanian Lanternfolk',
    kind: 'growth',
    race: 2,
    text: 'Draw 1. {dawn}: {shield:1}.',
    onPlay: [{ type: 'draw', amount: 1 }],
    onTurn: [{ type: 'shield', amount: 1 }],
  },
  {
    id: 'pressure_wave',
    name: 'Pressure Wave',
    kind: 'attack',
    race: 2,
    text: '{heat:2}. {shield:1}.',
    onPlay: [{ type: 'heat', amount: 2, to: 'target' }, { type: 'shield', amount: 1 }],
  },
  {
    id: 'coral_bastion',
    name: 'Coral Bastion',
    kind: 'defence',
    race: 2,
    text: '{bulwark:1}. {dawn}: {shield:2}.',
    onTurn: [{ type: 'shield', amount: 2 }],
    passive: [{ type: 'guard', amounts: [1] }],
  },
  {
    id: 'riptide',
    name: 'Riptide',
    kind: 'attack',
    race: 2,
    text: '{dawn}: {heat:1}. {heat:+1} per 3 shields you have (up to 3).',
    onTurn: [{ type: 'heat', amount: 1, to: 'target', plus: { of: 'shields', per: 3 }, max: 3 }],
  },
  {
    id: 'deep_hymn',
    name: 'Deep Hymn',
    kind: 'growth',
    race: 2,
    text: '{shield:3}. Draw 1.',
    onPlay: [{ type: 'shield', amount: 3 }, { type: 'draw', amount: 1 }],
  },
  {
    id: 'jelly_swarm',
    name: 'Vorthanian Swarm',
    kind: 'attack',
    race: 2,
    text: '{heat:1}. {heat:+1} per 2 defence cards (up to 3).',
    onPlay: [{ type: 'heat', amount: 1, to: 'target', plus: { of: 'kind', kind: 'defence', per: 2 }, max: 3 }],
  },
  {
    id: 'undertow_shrine',
    name: 'Undertow Shrine',
    kind: 'defence',
    race: 2,
    text: '{dusk}: {cool:1}. {soothe:1}.',
    onDusk: [{ type: 'cool', amount: 1 }],
    passive: [{ type: 'absorbCool', amount: 1 }],
  },
  { id: 'maelstrom', name: 'Maelstrom', kind: 'attack', race: 2, text: '{decay:1}. {shield:2}.', onPlay: [{ type: 'erode', amount: 1, all: true }, { type: 'shield', amount: 2 }] },
  {
    id: 'tidal_surge',
    name: 'Tidal Surge',
    kind: 'defence',
    race: 2,
    text: '{shield:2}. {shield:+2} while facing the abundant planet.',
    onPlay: [{ type: 'shield', amount: 2, plus: { of: 'planet', planet: 'abundant', amount: 2 } }],
  },
  {
    id: 'vorthane_elder',
    name: 'Vorthanian Elder',
    kind: 'defence',
    race: 2,
    text: '{dusk}: {cool:1}. {cool:+1} per 4 shields you have.',
    onDusk: [{ type: 'cool', amount: 1, plus: { of: 'shields', per: 4 } }],
  },
  {
    id: 'stinging_coral',
    name: 'Stinging Coral',
    kind: 'defence',
    race: 2,
    text: '{sting:2}. {dawn}: {shield:1}.',
    onTurn: [{ type: 'shield', amount: 1 }],
    passive: [{ type: 'retaliate', amount: 2 }],
  },
  { id: 'sunken_bell', name: 'Sunken Bell', kind: 'growth', race: 2, text: '{recall}. {shield:2}.', onPlay: [{ type: 'recall' }, { type: 'shield', amount: 2 }] },
  {
    id: 'ink_cloud',
    name: 'Ink Cloud',
    kind: 'lightspeed',
    race: 2,
    text: "{lightspeed}. When an enemy's card is about to heat your sun, first {shield:2}. Draw 1.",
    lightspeed: { trigger: { on: 'heated' }, effects: [{ type: 'shield', amount: 2 }, { type: 'draw', amount: 1 }] },
  },
  {
    id: 'abyssal_snap',
    name: 'Abyssal Snap',
    kind: 'lightspeed',
    race: 2,
    text: '{lightspeed}. When an enemy is about to destroy or return one of your cards, cancel it and {shield:3}.',
    lightspeed: { trigger: { on: 'targeted' }, counter: true, effects: [{ type: 'shield', amount: 3 }] },
  },
  { id: 'trench_warden', name: 'Vorthanian Trench-Warden', kind: 'defence', race: 2, text: '{guard}. {sturdy:3}. {dawn}: {shield:1}.', defence: 3, onTurn: [{ type: 'shield', amount: 1 }], passive: [{ type: 'taunt' }] },
  { id: 'tidebreaker', name: 'Tidebreaker', kind: 'attack', race: 2, text: '{eject:2}. {shield:2}.', onPlay: [{ type: 'bounce', maxDefence: 2 }, { type: 'shield', amount: 2 }] },

  // ---- Ixquor ----
  {
    id: 'spore_drone',
    name: 'Ixquor Spore-Drone',
    kind: 'growth',
    race: 3,
    text: '{dawn}: {grows:3}. {dusk}: {cool} equal to its growth.',
    onTurn: [{ type: 'grow', max: 3 }], onDusk: [{ type: 'cool', amount: 0, plus: { of: 'growth' } }],
  },
  {
    id: 'chitin_spire',
    name: 'Chitin Spire',
    kind: 'defence',
    race: 3,
    text: '{dawn}: {grows:3}, then {shield} equal to its growth.',
    onTurn: [{ type: 'grow', max: 3 }, { type: 'shield', amount: 0, plus: { of: 'growth' } }],
  },
  {
    id: 'hive_warrior',
    name: 'Ixquor Hive-Warrior',
    kind: 'attack',
    race: 3,
    text: '{dawn}: {heat:1}. {heat:+1} with 4+ cards.',
    onTurn: [{ type: 'heat', amount: 1, to: 'target' }, { type: 'heat', amount: 1, to: 'target', if: { minCards: 4 } }],
  },
  {
    id: 'seed_pod',
    name: 'Seed Pod',
    kind: 'growth',
    race: 3,
    text: 'Draw 1. When this leaves your tableau, {cool:1}.',
    onPlay: [{ type: 'draw', amount: 1 }],
    onLeave: [{ type: 'cool', amount: 1 }],
  },
  {
    id: 'bloom_burst',
    name: 'Bloom Burst',
    kind: 'attack',
    race: 3,
    text: '{heat:1} per 2 cards you control (up to 3). Draw 1.',
    onPlay: [{ type: 'heat', amount: 0, to: 'target', plus: { of: 'cards', per: 2 }, max: 3 }, { type: 'draw', amount: 1 }],
  },
  {
    id: 'creeping_vines',
    name: 'Creeping Vines',
    kind: 'attack',
    race: 3,
    text: '{erode:1}. {dawn}: {heat:1}.',
    onPlay: [{ type: 'erode', amount: 1 }],
    onTurn: [{ type: 'heat', amount: 1, to: 'target' }],
  },
  { id: 'hive_mind', name: 'Hive Mind', kind: 'growth', race: 3, text: '{dawn}: with 4+ cards, draw 1.', onTurn: [{ type: 'draw', amount: 1, if: { minCards: 4 } }] },
  {
    id: 'mycelial_net',
    name: 'Mycelial Net',
    kind: 'growth',
    race: 3,
    text: '{dawn}: your other cards grow 1. {dusk}: {cool:1}.',
    onTurn: [{ type: 'growOthers' }], onDusk: [{ type: 'cool', amount: 1 }],
  },
  {
    id: 'sporelings',
    name: 'Ixquor Sporelings',
    kind: 'growth',
    race: 3,
    text: '{energy:1}. {plant:1}.',
    onPlay: [{ type: 'plays', amount: 1 }, { type: 'plant', amount: 1 }],
  },
  {
    id: 'brood_chamber',
    name: 'Brood Chamber',
    kind: 'defence',
    race: 3,
    text: '{dawn}: {shield:1}. {shield:+1} per 3 cards you control.',
    onTurn: [{ type: 'shield', amount: 1, plus: { of: 'cards', per: 3 } }],
  },
  {
    id: 'spore_burst',
    name: 'Spore Burst',
    kind: 'attack',
    race: 3,
    text: '{heat:2}. {heat:+2} with 4+ cards.',
    onPlay: [{ type: 'heat', amount: 2, to: 'target' }, { type: 'heat', amount: 2, to: 'target', if: { minCards: 4 } }],
  },
  { id: 'root_network', name: 'Root Network', kind: 'growth', race: 3, text: '{recover}. {shield:1}.', onPlay: [{ type: 'recover', orDraw: 1 }, { type: 'shield', amount: 1 }] },
  { id: 'ixquor_gardener', name: 'Ixquor Gardener', kind: 'growth', race: 3, text: '{restore:2}. Draw 1.', onPlay: [{ type: 'restore', amount: 2 }, { type: 'draw', amount: 1 }] },
  {
    id: 'thorn_hedge',
    name: 'Thorn Hedge',
    kind: 'defence',
    race: 3,
    text: '{sturdy:1}. {sting:1}. {dusk}: {cool:1}.',
    defence: 1,
    onDusk: [{ type: 'cool', amount: 1 }],
    passive: [{ type: 'retaliate', amount: 1 }],
  },
  {
    id: 'husk_shell',
    name: 'Husk Shell',
    kind: 'defence',
    race: 3,
    text: '{shield:2}. When this leaves your tableau, {shield:2}.',
    onPlay: [{ type: 'shield', amount: 2 }],
    onLeave: [{ type: 'shield', amount: 2 }],
  },
  {
    id: 'ixquor_broodguard',
    name: 'Ixquor Broodguard',
    kind: 'defence',
    race: 3,
    text: '{guard}. {sturdy:1}. {dawn}: {shield:1}. {shield:+1} with 4+ cards.',
    defence: 1,
    onTurn: [{ type: 'shield', amount: 1 }, { type: 'shield', amount: 1, if: { minCards: 4 } }], passive: [{ type: 'taunt' }] },
  {
    id: 'spore_trap',
    name: 'Spore Trap',
    kind: 'lightspeed',
    race: 3,
    text: '{lightspeed}. When an enemy is about to destroy or return one of your cards, draw 2.',
    lightspeed: { trigger: { on: 'targeted' }, effects: [{ type: 'draw', amount: 2 }] },
  },
  {
    id: 'overgrowth',
    name: 'Overgrowth',
    kind: 'growth',
    race: 3,
    text: '{energy:2}. {heat:1} to your sun.',
    onPlay: [{ type: 'plays', amount: 2 }, { type: 'selfHeat', amount: 1 }],
  },
  {
    id: 'fruiting_body',
    name: 'Fruiting Body',
    kind: 'attack',
    race: 3,
    text: '{dusk}: {cool:1}. When this leaves your tableau, {heat:2}.',
    onDusk: [{ type: 'cool', amount: 1 }],
    onLeave: [{ type: 'heat', amount: 2, to: 'target' }],
  },
  {
    id: 'hive_tyrant',
    name: 'Ixquor Hive-Tyrant',
    kind: 'attack',
    race: 3,
    text: '{heat:1}. {dawn}: {heat:1} per 2 cards you control (up to 2).',
    onPlay: [{ type: 'heat', amount: 1, to: 'target' }],
    onTurn: [{ type: 'heat', amount: 0, to: 'target', plus: { of: 'cards', per: 2 }, max: 2 }],
  },
  // ---- Defence that answers a big attack at once: shields and cooling as they land, more each dawn ----
  { id: 'frost_bulwark', name: 'Frost Bulwark', kind: 'defence', text: '{cool:2}. {shield:2}.', onPlay: [{ type: 'cool', amount: 2 }, { type: 'shield', amount: 2 }] },
  {
    id: 'glacier_shell',
    name: 'Glacier Shell',
    kind: 'defence',
    text: '{shield:3}. {dusk}: {cool:2}.',
    onPlay: [{ type: 'shield', amount: 3 }],
    onDusk: [{ type: 'cool', amount: 2 }],
  },
  { id: 'stellar_aegis', name: 'Stellar Aegis', kind: 'defence', text: '{shield:10}. {cool:3}.', onPlay: [{ type: 'shield', amount: 10 }, { type: 'cool', amount: 3 }] },
  {
    id: 'solar_bastion',
    name: 'Solar Bastion',
    kind: 'defence',
    text: '{guard}. {shield:6}. {cool:2}. {dawn}: {shield:2}. {dusk}: {cool:1}.',
    onPlay: [{ type: 'shield', amount: 6 }, { type: 'cool', amount: 2 }],
    onTurn: [{ type: 'shield', amount: 2 }], onDusk: [{ type: 'cool', amount: 1 }], passive: [{ type: 'taunt' }] },
  {
    id: 'dawn_rampart',
    name: 'Dawn Rampart',
    kind: 'defence',
    race: 0,
    text: '{shield:2}. {cool:1}. {dawn}: {shield:1}.',
    onPlay: [{ type: 'shield', amount: 2 }, { type: 'cool', amount: 1 }],
    onTurn: [{ type: 'shield', amount: 1 }],
  },
  {
    id: 'prism_sanctum',
    name: 'Prism Sanctum',
    kind: 'defence',
    race: 1,
    text: '{cool:4}. {dusk}: {cool:1}. {cool:+1} while {overheated}.',
    onPlay: [{ type: 'cool', amount: 4 }],
    onDusk: [{ type: 'cool', amount: 1 }, { type: 'cool', amount: 1, if: { overheated: true } }],
  },
  {
    id: 'leviathan_shell',
    name: 'Leviathan Shell',
    kind: 'defence',
    race: 2,
    text: '{guard}. {shield:6}. {hold:12}. {dawn}: {shield:2}.',
    onPlay: [{ type: 'shield', amount: 6 }],
    onTurn: [{ type: 'shield', amount: 2 }],
    passive: [{ type: 'taunt' }, { type: 'keepShields' }],
  },
  {
    id: 'chitin_fortress',
    name: 'Chitin Fortress',
    kind: 'defence',
    race: 3,
    text: '{guard}. {sturdy:1}. {shield:3}. {dusk}: {cool:1}. {cool:+1} with 4+ cards.',
    defence: 1,
    onPlay: [{ type: 'shield', amount: 3 }],
    onDusk: [{ type: 'cool', amount: 1 }, { type: 'cool', amount: 1, if: { minCards: 4 } }], passive: [{ type: 'taunt' }] },
  // ---- Energy dumps: spend all your energy (X), for an effect that grows with every point of it ----
  {
    id: 'solar_torrent',
    name: 'Solar Torrent',
    kind: 'attack',
    spendAll: true,
    text: '{spend}. {heat:1}. {heat:+2} per energy spent.',
    onPlay: [{ type: 'heat', amount: 1, to: 'target', plus: { of: 'spent', times: 2 } }],
  },
  {
    id: 'deep_freeze',
    name: 'Deep Freeze',
    kind: 'defence',
    spendAll: true,
    text: '{spend}. {cool:1}. {cool:+1} and {shield:1} per energy spent.',
    onPlay: [{ type: 'cool', amount: 1, plus: { of: 'spent' } }, { type: 'shield', amount: 0, plus: { of: 'spent' } }],
  },
  {
    id: 'overflow_archive',
    name: 'Overflow Archive',
    kind: 'growth',
    spendAll: true,
    text: '{spend}. Draw 1 per energy spent.',
    onPlay: [{ type: 'draw', amount: 0, plus: { of: 'spent' } }],
  },
  {
    id: 'radiant_barrage',
    name: 'Radiant Barrage',
    kind: 'attack',
    race: 0,
    spendAll: true,
    text: '{spend}. {heat:1} and {shield:1} per energy spent.',
    onPlay: [{ type: 'heat', amount: 0, to: 'target', plus: { of: 'spent' } }, { type: 'shield', amount: 0, plus: { of: 'spent' } }],
  },
  {
    id: 'meltdown',
    name: 'Meltdown',
    kind: 'attack',
    race: 1,
    spendAll: true,
    text: '{spend}. {heat:2}, {pierce}. {heat:+1} per energy spent. {heat:2} to your sun.',
    onPlay: [{ type: 'heat', amount: 2, to: 'target', plus: { of: 'spent' }, pierce: true }, { type: 'selfHeat', amount: 2 }],
  },
  {
    id: 'abyssal_rampart',
    name: 'Abyssal Rampart',
    kind: 'defence',
    race: 2,
    spendAll: true,
    text: '{spend}. {shield:2} per energy spent.',
    onPlay: [{ type: 'shield', amount: 0, plus: { of: 'spent', times: 2 } }],
  },
  {
    id: 'hive_surge',
    name: 'Hive Surge',
    kind: 'growth',
    race: 3,
    spendAll: true,
    text: '{spend}. Draw 1 and {cool:1} per energy spent.',
    onPlay: [{ type: 'draw', amount: 0, plus: { of: 'spent' } }, { type: 'cool', amount: 0, plus: { of: 'spent' } }],
  },
  // ---- Bombs: the big cards (3-5 energy), so every deck has something to ramp into ----
  { id: 'dawnstar_cannon', name: 'Dawnstar Cannon', kind: 'attack', race: 0, text: '{sturdy:1}. {dawn}: {heat:3}.', defence: 1, onTurn: [{ type: 'heat', amount: 3, to: 'target' }] },
  { id: 'aureline_sunguard', name: 'Aureline Sunguard', kind: 'defence', race: 0, text: '{guard}. {sturdy:2}. {shield:3}. {dawn}: {shield:2}.', defence: 2, onPlay: [{ type: 'shield', amount: 3 }], onTurn: [{ type: 'shield', amount: 2 }], passive: [{ type: 'taunt' }] },
  { id: 'hymn_of_the_sun', name: 'Hymn of the Sun', kind: 'attack', race: 0, text: '{heat:2}. {dawn}: {heat:2}. {heat:+1} per 2 attack cards you control (up to 2).', onPlay: [{ type: 'heat', amount: 2, to: 'target' }], onTurn: [{ type: 'heat', amount: 2, to: 'target', plus: { of: 'kind', kind: 'attack', per: 2 }, max: 4 }] },
  { id: 'prism_colossus', name: 'Prism Colossus', kind: 'attack', race: 1, text: '{dawn}: {heat:3}, {pierce}. When this leaves your tableau, {heat:4}.', onTurn: [{ type: 'heat', amount: 3, to: 'target', pierce: true }], onLeave: [{ type: 'heat', amount: 4, to: 'target' }] },
  { id: 'shard_tempest', name: 'Shard Tempest', kind: 'attack', race: 1, text: '{heat:5}. {heat:+2} while {overheated}. {heat:2} to your sun.', onPlay: [{ type: 'heat', amount: 5, to: 'target' }, { type: 'heat', amount: 2, to: 'target', if: { overheated: true } }, { type: 'selfHeat', amount: 2 }] },
  { id: 'crystal_reliquary', name: 'Crystal Reliquary', kind: 'growth', race: 1, text: '{recover}. Draw 2.', onPlay: [{ type: 'recover', orDraw: 1 }, { type: 'draw', amount: 2 }] },
  { id: 'abyssal_titan', name: 'Abyssal Titan', kind: 'defence', race: 2, text: '{guard}. {sturdy:2}. {sting:2}. {dawn}: {shield:3}.', defence: 2, onTurn: [{ type: 'shield', amount: 3 }], passive: [{ type: 'taunt' }, { type: 'retaliate', amount: 2 }] },
  { id: 'tidal_wave', name: 'Tidal Wave', kind: 'attack', race: 2, text: '{heat:3}. {heat:+1} per 2 shields you have (up to 7).', onPlay: [{ type: 'heat', amount: 3, to: 'target', plus: { of: 'shields', per: 2 }, max: 7 }] },
  { id: 'pressure_dome', name: 'Pressure Dome', kind: 'defence', race: 2, text: '{shield:5}. {dawn}: {shield:2}.', onPlay: [{ type: 'shield', amount: 5 }], onTurn: [{ type: 'shield', amount: 2 }] },
  { id: 'hive_colossus', name: 'Hive Colossus', kind: 'attack', race: 3, text: '{dawn}: {heat:2}. {heat:+1} per 2 cards you control (up to 3).', onTurn: [{ type: 'heat', amount: 2, to: 'target', plus: { of: 'cards', per: 2 }, max: 5 }] },
  { id: 'sporestorm', name: 'Sporestorm', kind: 'attack', race: 3, text: '{heat:2}. {heat:+1} per card you control (up to 5).', onPlay: [{ type: 'heat', amount: 2, to: 'target', plus: { of: 'cards' }, max: 7 }] },
  { id: 'great_mycelium', name: 'Great Mycelium', kind: 'growth', race: 3, text: '{abundance:1}. {dusk}: {cool:1}. {cool:+1} with 4+ cards.', onTurn: [{ type: 'draw', amount: 1 }], onDusk: [{ type: 'cool', amount: 1 }, { type: 'cool', amount: 1, if: { minCards: 4 } }] },
  { id: 'dreadnought', name: 'Dreadnought', kind: 'attack', text: '{sturdy:2}. {dawn}: {heat:4}.', defence: 2, onTurn: [{ type: 'heat', amount: 4, to: 'target' }] },
  { id: 'star_breaker', name: 'Star Breaker', kind: 'attack', text: '{destroy:4}. {heat:3}.', onPlay: [{ type: 'destroy', maxDefence: 4 }, { type: 'heat', amount: 3, to: 'target' }] },
  { id: 'fusion_reactor', name: 'Fusion Reactor', kind: 'growth', text: '{plays:1}.', passive: [{ type: 'extraPlay', amount: 1 }] },
];

/** The second set's rarities and characters (as CARD_META in cards.ts). */
export const EXPANSION_META: Record<string, { rarity?: Rarity; character?: boolean }> = {
  aureline_sunguard: { character: true },
  hymn_of_the_sun: { rarity: 'stellar' },
  prism_colossus: { character: true, rarity: 'stellar' },
  abyssal_titan: { character: true, rarity: 'stellar' },
  hive_colossus: { character: true, rarity: 'stellar' },
  dreadnought: { rarity: 'stellar' },
  star_breaker: { rarity: 'stellar' },
  // Neutral
  solar_torrent: { rarity: 'stellar' },
  meltdown: { rarity: 'stellar' },
  overflow_archive: { rarity: 'stellar' },
  stellar_aegis: { rarity: 'stellar' },
  solar_bastion: { rarity: 'stellar' },
  leviathan_shell: { rarity: 'stellar' },
  prism_sanctum: { rarity: 'stellar' },
  siege_array: { rarity: 'stellar' },
  void_bolt: { rarity: 'stellar' },
  bastion_node: { rarity: 'stellar' },
  blink_bulwark: { rarity: 'stellar' },
  riptide_sentinel: { rarity: 'stellar' },
  gravity_well: { rarity: 'stellar' },
  archive_vault: { rarity: 'stellar' },
  counter_pulse: { rarity: 'stellar' },
  war_council: { character: true },
  logistics_command: { character: true },
  absolute_zero: { rarity: 'anomaly' },
  orion_galaxy_eater: { character: true, rarity: 'anomaly' },
  frostbound_sentinel: { character: true },
  glacier_hull: { rarity: 'stellar' },
  empress_solenne: { character: true, rarity: 'anomaly' },
  the_shardmind: { character: true, rarity: 'anomaly' },
  leviathan_thoross: { character: true, rarity: 'anomaly' },
  the_worldroot: { character: true, rarity: 'anomaly' },
  // Aureline
  aureline_skirmisher: { character: true },
  lancer_squadron: { character: true, rarity: 'stellar' },
  aureline_archon: { character: true, rarity: 'stellar' },
  the_sun_throne: { rarity: 'anomaly' },
  aureline_cantor: { character: true },
  halo_sentinel: { character: true },
  prism_of_dawn: { rarity: 'stellar' },
  aureline_quartermaster: { character: true },
  aureline_vanguard: { character: true },
  radiant_hymn: { rarity: 'stellar' },
  // Xel'Naru
  shard_lancer: { character: true },
  xelnaru_oracle: { character: true, rarity: 'stellar' },
  molten_cascade: { rarity: 'stellar' },
  crystal_matrix: { rarity: 'stellar' },
  xelnaru_warden: { character: true },
  refraction_veil: { rarity: 'stellar' },
  shard_mother: { character: true, rarity: 'stellar' },
  fracture_burst: { rarity: 'stellar' },
  // Vorthane
  vorthane_tidecaller: { character: true },
  abyss_lantern: { character: true },
  jelly_swarm: { character: true },
  coral_bastion: { rarity: 'stellar' },
  maelstrom: { rarity: 'stellar' },
  vorthane_elder: { character: true, rarity: 'stellar' },
  abyssal_snap: { rarity: 'stellar' },
  trench_warden: { character: true },
  // Ixquor
  spore_drone: { character: true },
  hive_warrior: { character: true },
  ixquor_broodguard: { character: true },
  sporelings: { character: true, rarity: 'stellar' },
  ixquor_gardener: { character: true },
  spore_burst: { rarity: 'stellar' },
  overgrowth: { rarity: 'stellar' },
  hive_tyrant: { character: true, rarity: 'stellar' },
};
