/**
 * The cards the space adventure offers (at space stations, as rewards), by id: its own list, taken from the
 * card game's when the adventure began. A card game card joins it only when added here.
 */
export const VOYAGE_POOL: string[] = [
  'coronal_lance', 'plasma_relay', 'gravity_sling', 'thermal_exchange', 'solar_battery', 'ion_cannon',
  'coolant_array', 'cryo_vault', 'deflector_grid', 'heat_sink', 'deep_scanners', 'command_directive',
  'ignition_protocol', 'coolant_protocol', 'tide_regent', 'the_admiralty', 'chamber_protocol', 'standing_orders',
  'chain_of_command', 'resonance_lattice', 'harmonic_singularity', 'bulwark_plating', 'aegis_monolith',
  'chrono_anchor', 'stasis_field', 'entropy_pulse', 'decay_wave', 'salvage_drone', 'phase_shift', 'tractor_beam',
  'command_breaker', 'event_horizon', 'null_field', 'signal_jammer', 'frost_snare', 'solar_mirror', 'decoy_array',
  'temporal_snare', 'helio_lancer', 'focusing_array', 'coronal_chorus', 'sunspear', 'dawn_beacon', 'halo_ward',
  'shard_reactor', 'crystal_storm', 'overload_core', 'martyr_crystal', 'prism_vent', 'fracture_lens', 'bell_warden',
  'stinging_veil', 'tidal_bloom', 'abyssal_choir', 'deep_current', 'lure_jelly', 'mycelium_tower', 'hive_relay',
  'sporecaster', 'rot_bloom', 'canopy', 'spore_cloud', 'shard_renewal', 'undertow', 'hive_rooting',
  'aureline_war_herald', 'sunforge', 'ember_shard', 'xelnaru_reliquarist', 'prism_conduit', 'tide_pylon',
  'riptide_ambush', 'regrowth_pod', 'spore_husk', 'aureline_sun_priest', 'aurelia_first_light', 'xelnaru_champion',
  'kyrvessa_prism_queen', 'hero_of_rathune', 'ommarath_deep_bell', 'ixquor_brood_tender', 'the_brood_queen',
  'gravity_assist', 'orbital_slingshot', 'tidal_brake', 'dead_world_mine', 'perihelion_forge', 'sunward_lance',
  'comet_shard', 'tide_lock', 'orbit_root', 'recall_beacon', 'sunlit_return', 'shard_recall', 'returning_tide',
  'compost_cycle', 'nova_shell', 'photon_drill', 'ember_drone', 'siege_array', 'scatter_shot', 'flux_lance',
  'void_bolt', 'comet_hail', 'frost_lattice', 'mirror_plating', 'cold_front', 'radiator_fins', 'bastion_node',
  'blink_bulwark', 'sunflash_aegis', 'riptide_sentinel', 'debris_field', 'survey_probe', 'star_chart', 'gravity_well',
  'relay_station', 'archive_vault', 'supply_cache', 'flare_trap', 'counter_pulse', 'snare_beacon', 'ghost_signal',
  'war_council', 'logistics_command', 'absolute_zero', 'cryo_lance', 'rime_bastion', 'frostbound_sentinel',
  'glacier_hull', 'thaw_beam', 'orion_galaxy_eater', 'empress_solenne', 'the_shardmind', 'leviathan_thoross',
  'the_worldroot', 'aureline_skirmisher', 'dawnblade', 'lancer_squadron', 'aureline_archon', 'the_sun_throne',
  'gilded_lens', 'radiant_hymn', 'solar_aegis', 'aureline_cantor', 'lance_volley', 'glory_charge', 'banner_of_dawn',
  'halo_sentinel', 'prism_of_dawn', 'sunfire_volley', 'aureline_quartermaster', 'helio_bastion', 'aureline_vanguard',
  'sunlance_charge', 'shard_lancer', 'searing_core', 'crystal_bloom', 'fault_line', 'echo_shard', 'shatter_point',
  'prism_ward', 'xelnaru_oracle', 'molten_cascade', 'shard_storm', 'heat_bleed', 'crystal_matrix', 'xelnaru_warden',
  'shard_echo', 'tactical_withdrawal', 'rally_banner', 'spore_return', 'overcharge', 'refraction_veil',
  'shard_mother', 'fracture_burst', 'cinder_ward', 'vorthane_tidecaller', 'brine_lash', 'kelp_wall', 'abyss_lantern',
  'pressure_wave', 'coral_bastion', 'riptide', 'deep_hymn', 'jelly_swarm', 'undertow_shrine', 'maelstrom',
  'tidal_surge', 'vorthane_elder', 'stinging_coral', 'sunken_bell', 'ink_cloud', 'abyssal_snap', 'trench_warden',
  'tidebreaker', 'spore_drone', 'chitin_spire', 'hive_warrior', 'seed_pod', 'bloom_burst', 'creeping_vines',
  'hive_mind', 'mycelial_net', 'sporelings', 'brood_chamber', 'spore_burst', 'root_network', 'ixquor_gardener',
  'thorn_hedge', 'husk_shell', 'ixquor_broodguard', 'spore_trap', 'overgrowth', 'fruiting_body', 'hive_tyrant',
  'frost_bulwark', 'glacier_shell', 'stellar_aegis', 'solar_bastion', 'dawn_rampart', 'prism_sanctum',
  'leviathan_shell', 'chitin_fortress', 'solar_torrent', 'deep_freeze', 'overflow_archive', 'radiant_barrage',
  'meltdown', 'abyssal_rampart', 'hive_surge', 'dawnstar_cannon', 'aureline_sunguard', 'hymn_of_the_sun',
  'prism_colossus', 'shard_tempest', 'crystal_reliquary', 'abyssal_titan', 'tidal_wave', 'pressure_dome',
  'hive_colossus', 'sporestorm', 'great_mycelium', 'dreadnought', 'star_breaker', 'fusion_reactor', 'spore_catalyst',
  'seed_burst', 'orrery', 'ecliptic_lance', 'solstice_choir', 'precession_engine', 'moon_warden', 'seasonal_bloom',
  'grand_orrery', 'nyx_umbral_snare', 'nyx_mirror_veil', 'nyx_night_ambush', 'nyx_null_shroud', 'nyx_veil_sentry',
  'nyx_gloom_warden', 'nyx_veil_lantern', 'nyx_shade_stalker', 'nyx_dusk_raider', 'nyx_unmaker_blade',
  'nyx_void_rend', 'nyx_unravel', 'nyx_phantom_strike', 'nyx_hollow_reaper', 'nyx_shadow_court', 'nyx_eclipse_rite',
  'nyx_hero_vesh', 'nyx_hero_kael', 'nyx_hero_nyxara', 'kor_forge_hammer', 'kor_master_smith', 'kor_ore_hauler',
  'kor_shieldwall', 'kor_bastion_kin', 'kor_iron_sentinel', 'kor_rampart_lord', 'kor_siege_ram', 'kor_foundry',
  'kor_molten_pour', 'kor_temper', 'kor_hero_durga', 'kor_hero_brannoc', 'kor_hero_anvil_king', 'ser_astral_lance',
  'ser_tide_turner', 'ser_planet_shepherd', 'ser_eclipse_caster', 'ser_twin_moons', 'ser_star_chart',
  'ser_orrery_keeper', 'ser_stargazer', 'ser_oracle', 'ser_lantern_of_ages', 'ser_moonwell', 'ser_constellation',
  'ser_star_needle', 'ser_almanac', 'ser_hero_ilyath', 'ser_hero_maren', 'ser_hero_aster', 'pyr_flare_imp',
  'pyr_cinder_brute', 'pyr_ash_walker', 'pyr_heat_bloom', 'pyr_ember_guard', 'pyr_magma_heart', 'pyr_flare_burst',
  'pyr_supernova_charge', 'pyr_pyre_shield', 'pyr_flarekin_dancer', 'pyr_stoker', 'pyr_flare_temple',
  'pyr_vent_cooler', 'pyr_solar_tyrant', 'pyr_hero_ignis', 'pyr_hero_ashka', 'pyr_hero_pyrrhus', 'twilight_sentry',
  'evening_star', 'gloaming_battery', 'vesper_bell', 'aureline_vesper_knight', 'shard_twilight', 'ebb_tide',
  'night_bloom', 'nyx_nightfall', 'kor_banked_forge', 'ser_evening_vigil', 'pyr_banked_embers', 'coronal_storm',
  'furnace_engine', 'bulwark_prime', 'zenith_array', 'supernova_lance', 'great_collapse', 'dyson_sphere', 'black_sun',
  'ember_idol', 'frost_reliquary', 'aegis_idol', 'chrono_stone', 'warden_totem', 'tide_pearl', 'astral_orrery',
  'crown_first_sun',
];
